# Generated by Django 5.0.14 on 2026-02-01 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('change_type', models.CharField(choices=[('NEW', 'New File'), ('MODIFIED', 'Modified'), ('DELETED', 'Deleted'), ('PERM', 'Permission Change')], max_length=10)),
                ('old_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('new_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Mark if alert has been acknowledged')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Absolute path to the directory', max_length=500, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Enable or disable monitoring for this path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('file_hash', models.CharField(help_text='SHA-256 Hash', max_length=64)),
                ('last_modified', models.FloatField(help_text='Timestamp from os.stat')),
                ('last_scanned', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.monitoreddirectory')),
            ],
        ),
    ]
